/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Produtos;

import java.awt.Insets;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aluno
 */
public class FormProduto extends javax.swing.JDialog {

    /**
     * Creates new form FormProduto
     */
    public FormProduto() {
        initComponents();
        if (ClassP == null) {
            ClassP = new ClasseProduto();
        }
        preenche();
    }
    private ClasseProduto ClassP;
    private boolean salvaEdita = false;
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbSair = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        cmbCategoria = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtICMS = new javax.swing.JTextField();
        cmbAliquota1 = new javax.swing.JComboBox();
        cmbAliquota2 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        txtIdProduto = new javax.swing.JTextField();
        btNovo = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblproduto = new javax.swing.JTable();
        btEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PubManager V1.0 Cadastro Produtos");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBackground(new java.awt.Color(240, 204, 153));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo PubMng2.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(240, 204, 153));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Cadastro de Produtos");

        lbSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        lbSair.setToolTipText("");
        lbSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSairMouseClicked(evt);
            }
        });

        jLabel8.setText("Sair");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSair)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbSair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Dados do Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Descrição:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Categoria:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Preço:");

        txtDescricao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDescricao.setEnabled(false);

        txtValor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtValor.setEnabled(false);

        cmbCategoria.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BEBIDAS", "PORÇÕES", "REFEIÇÕES", "PIZZAS", "LANCHES", "SOBREMESAS", "APERITIVOS" }));
        cmbCategoria.setSelectedIndex(-1);
        cmbCategoria.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("ICMS:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Aliquota:");

        txtICMS.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtICMS.setEnabled(false);

        cmbAliquota1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbAliquota1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0 - Mercadoria Nacional", "1 - Mercadoria estrangeira de importação direta", "2 - Mercadoria estrangeira adquirida no mercado interno" }));
        cmbAliquota1.setSelectedIndex(-1);
        cmbAliquota1.setEnabled(false);

        cmbAliquota2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cmbAliquota2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00 - Tributada integralmente", "10 - Tributada e com cobrança do ICMS por substituição tributária", "20 - Com redução de base de cálculo", "30 - Isenta ou não tributada e com cobrança do ICMS  por substituição tributária", "40 - Isenta", "41 - Não tributada", "50 - Suspensão", "51 - Diferimento", "60 - ICMS cobrado anteriormente por substituição tributária", "70 - Com redução de base de cálculo e cobrança do ICMS por substituição tributária", "90 - Outras" }));
        cmbAliquota2.setSelectedIndex(-1);
        cmbAliquota2.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("ID Produto:");

        txtIdProduto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtIdProduto.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(21, 21, 21)
                                .addComponent(txtICMS, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescricao)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbAliquota1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbAliquota2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(423, 423, 423)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtICMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAliquota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbAliquota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btNovo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add.png"))); // NOI18N
        btNovo.setText("<html>Novo<br>Produto</html>");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btSalvar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Save.png"))); // NOI18N
        btSalvar.setText("<html>Salvar<br>Produto</html>");
        btSalvar.setEnabled(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btBuscar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search.png"))); // NOI18N
        btBuscar.setText("<html>Buscar<br>Produto</html>");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        tblproduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblproduto.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblproduto.getTableHeader().setResizingAllowed(false);
        tblproduto.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblproduto);

        btEditar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Edit_text.png"))); // NOI18N
        btEditar.setText("<html>Editar<br>Produto</html>");
        btEditar.setEnabled(false);
        btEditar.setMaximumSize(new java.awt.Dimension(111, 41));
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    public void preenche() {
        String aux2 = "SELECT * FROM produtos";

        while (tblproduto.getRowCount() > 0) {
            ((DefaultTableModel) tblproduto.getModel()).removeRow(0);
        }
        ((DefaultTableModel) tblproduto.getModel()).setColumnCount(0);

        tblproduto.setModel(ClassP.preencheTabela(aux2));
        
        tblproduto.getTableHeader().setReorderingAllowed(false);
                
        tblproduto.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        for (int i = 0; i <= 5; i++) {
            tblproduto.getColumnModel().getColumn(i).setPreferredWidth(127);
        }
    }
    
    
    public void preencheClasse() {
        ClassP.setIdProduto(Integer.valueOf(txtIdProduto.getText()));
        ClassP.setDescricao(txtDescricao.getText().toUpperCase());
        ClassP.setPreco(Float.valueOf(txtValor.getText().replaceAll(",", ".")));
        ClassP.setCategoria(String.valueOf(cmbCategoria.getSelectedItem()).toUpperCase());
        ClassP.setICMS(Float.valueOf(txtICMS.getText().replaceAll(",", ".")));
        ClassP.setAliquota(String.valueOf(cmbAliquota1.getSelectedItem()).substring(0, 1) + ""
                + String.valueOf(cmbAliquota2.getSelectedItem()).substring(0, 2));
    }

    public void limpaFrame() {
        txtIdProduto.setText("");
        txtDescricao.setText("");
        txtICMS.setText("");
        txtValor.setText("");
        cmbCategoria.setSelectedIndex(-1);
        cmbAliquota1.setSelectedIndex(-1);
        cmbAliquota2.setSelectedIndex(-1);
    }

    public void desbloqueia() {
        txtDescricao.setEnabled(true);
        txtICMS.setEnabled(true);
        txtValor.setEnabled(true);
        cmbCategoria.setEnabled(true);
        cmbAliquota1.setEnabled(true);
        cmbAliquota2.setEnabled(true);
        btNovo.setEnabled(false);
        btSalvar.setEnabled(true);
        btBuscar.setEnabled(false);
    }

    public void bloqueia() {
        txtDescricao.setEnabled(false);
        txtICMS.setEnabled(false);
        txtValor.setEnabled(false);
        cmbCategoria.setEnabled(false);
        cmbAliquota1.setEnabled(false);
        cmbAliquota2.setEnabled(false);
        btSalvar.setEnabled(false);
        btEditar.setEnabled(false);
        btBuscar.setEnabled(true);
        btNovo.setEnabled(true);
        preenche();
    }

    public void preencheCampos(){
        txtDescricao.setText(ClassP.getDescricao());
        txtIdProduto.setText(String.valueOf(ClassP.getIdProduto()));
        txtICMS.setText(String.valueOf(ClassP.getICMS()));
        txtValor.setText(String.valueOf(ClassP.getPreco()));
        cmbCategoria.setSelectedItem(ClassP.getCategoria());
        cmbAliquota1.setSelectedIndex(Integer.valueOf(ClassP.getAliquota().substring(0, 1)));
        switch(ClassP.getAliquota().substring(1, 3)){
            case "00":
                cmbAliquota2.setSelectedIndex(0);
                break;
            case "10":
                cmbAliquota2.setSelectedIndex(1);
                break;
            case "20":
                cmbAliquota2.setSelectedIndex(2);
                break;
            case "30":
                cmbAliquota2.setSelectedIndex(3);
                break;
            case "40":
                cmbAliquota2.setSelectedIndex(4);
                break;
            case "41":
                cmbAliquota2.setSelectedIndex(5);
                break;
            case "50":
                cmbAliquota2.setSelectedIndex(6);
                break;
            case "51":
                cmbAliquota2.setSelectedIndex(7);
                break;
            case "60":
                cmbAliquota2.setSelectedIndex(8);
                break;
            case "70":
                cmbAliquota2.setSelectedIndex(9);
                break;
            case "90":
                cmbAliquota2.setSelectedIndex(10);
                break;
        }
        
    }

    private void lbSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSairMouseClicked
        if (JOptionPane.showConfirmDialog(null,"Deseja fechar esta janela e\nRetornar ao Menu Principal?\n"+
                "Obs: Todos os dados que não\nForem salvos serão Perdidos!","Cadastro de Produtos",JOptionPane.YES_NO_OPTION) ==
                JOptionPane.YES_OPTION){
            limpaFrame();
            bloqueia();
            this.dispose();
        }
        
    }//GEN-LAST:event_lbSairMouseClicked

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (!txtDescricao.getText().equalsIgnoreCase("")) {
            if (!txtValor.getText().equalsIgnoreCase("")) {
                if (!txtICMS.getText().equalsIgnoreCase("")) {
                    if (cmbCategoria.getSelectedIndex() != -1) {
                        if (cmbAliquota1.getSelectedIndex() != -1 && cmbAliquota2.getSelectedIndex() != -1) {

                            preencheClasse();
                            ClassP.insereProduto(ClassP);
                            limpaFrame();
                            bloqueia();

                        } else {
                            JOptionPane.showMessageDialog(this, "Categoria de Aliquota Inválida!",
                                    "Cadastro de Produtos", JOptionPane.WARNING_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Categoria Inválida!",
                                "Cadastro de Produtos", JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Valor do ICMS Inválido!",
                            "Cadastro de Produtos", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Preço Inválido!",
                        "Cadastro de Produtos", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nome Inválido!",
                    "Cadastro de Produtos", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        limpaFrame();
        txtIdProduto.setText(String.valueOf(ClassP.ultimoID("Select Max(IdProdutos) from produtos")));
        desbloqueia();
    }//GEN-LAST:event_btNovoActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        ClassP.setIdProduto(Integer.valueOf(JOptionPane.showInputDialog(this,
                "Insira o ID do produto","Busca Produtos",JOptionPane.PLAIN_MESSAGE)));
        
        if (ClassP.buscaProduto(ClassP)){
            preencheCampos();
            btEditar.setEnabled(true);
        }else{
            JOptionPane.showMessageDialog(null,"Produto não cadastrado","Cadastro de Produtos",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        if (salvaEdita == false) {
            if (JOptionPane.showConfirmDialog(this, "Deseja Alterar os\nDados do Produto?", "Cadastro Produtos",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                desbloqueia();
                btSalvar.setEnabled(false);
                btEditar.setMargin(new Insets(2, 7, 2, 7));
                btEditar.setText("<html>Salvar<br>Alterações</html>");
                salvaEdita = true;
            }
        } else {
            if (JOptionPane.showConfirmDialog(this, "Deseja Salvar os Dados Alterados?", "Cadastro Produtos",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                if (!txtDescricao.getText().equalsIgnoreCase("")) {
                    if (!txtValor.getText().equalsIgnoreCase("")) {
                        if (!txtICMS.getText().equalsIgnoreCase("")) {
                            if (cmbCategoria.getSelectedIndex() != -1) {
                                if (cmbAliquota1.getSelectedIndex() != -1 && cmbAliquota2.getSelectedIndex() != -1) {

                                    preencheClasse();
                                    ClassP.alteraProduto(ClassP);
                                    limpaFrame();
                                    bloqueia();
                                    btEditar.setMargin(new Insets(2, 14, 2, 14));
                                    btEditar.setText("<html>Editar<br>Produto</html>");
                                    salvaEdita = false;
                                } else {
                                    JOptionPane.showMessageDialog(this, "Categoria de Aliquota Inválida!",
                                            "Cadastro de Produtos", JOptionPane.WARNING_MESSAGE);
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "Categoria Inválida!",
                                        "Cadastro de Produtos", JOptionPane.WARNING_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Valor do ICMS Inválido!",
                                    "Cadastro de Produtos", JOptionPane.WARNING_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Preço Inválido!",
                                "Cadastro de Produtos", JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Nome Inválido!",
                            "Cadastro de Produtos", JOptionPane.WARNING_MESSAGE);
                }
            }
            
        }
        
        
        
        
        
        
    }//GEN-LAST:event_btEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox cmbAliquota1;
    private javax.swing.JComboBox cmbAliquota2;
    private javax.swing.JComboBox cmbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbSair;
    private javax.swing.JTable tblproduto;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtICMS;
    private javax.swing.JTextField txtIdProduto;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
