/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Delivery;

import Clientes.frmClientes;
import Delivery.frmNovoPedido;

/**
 *
 * @author Aluno
 */
public class frmDeliveryInicio extends javax.swing.JFrame {

    /**
     * Creates new form frmDeliveryInicio
     */
    public frmDeliveryInicio() {
        initComponents();
        
        //this.setIconImage(ImageIO.read(new File("")));
        
    }
    
    private frmClientes frmCli;
    private frmNovoPedido frmPedido;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        pnChamados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbChamados = new javax.swing.JTable();
        pnDados = new javax.swing.JPanel();
        lbNomeCliente = new javax.swing.JLabel();
        lbEnderecoCliente = new javax.swing.JLabel();
        lbTelefoneCliente = new javax.swing.JLabel();
        lbTextoNome = new javax.swing.JLabel();
        lbTextoEndereco = new javax.swing.JLabel();
        lbTextoTelefone = new javax.swing.JLabel();
        pnPedido = new javax.swing.JPanel();
        lbTotalItens = new javax.swing.JLabel();
        lbTotalPedido = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbTextoTotalItens = new javax.swing.JLabel();
        lbTextoPrecoTotal = new javax.swing.JLabel();
        pnControle = new javax.swing.JPanel();
        btAddPedido = new javax.swing.JButton();
        btAddUser = new javax.swing.JButton();
        btVerRelatorio = new javax.swing.JButton();
        btRefresh = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btImprimir = new javax.swing.JButton();
        lbLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PubManager - Delivery");
        setUndecorated(true);

        pnChamados.setBackground(new java.awt.Color(255, 255, 255));
        pnChamados.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbChamados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbChamados);

        javax.swing.GroupLayout pnChamadosLayout = new javax.swing.GroupLayout(pnChamados);
        pnChamados.setLayout(pnChamadosLayout);
        pnChamadosLayout.setHorizontalGroup(
            pnChamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        pnChamadosLayout.setVerticalGroup(
            pnChamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
        );

        pnDados.setBackground(new java.awt.Color(255, 255, 255));
        pnDados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DADOS", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        lbNomeCliente.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lbNomeCliente.setText("NOME:");

        lbEnderecoCliente.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lbEnderecoCliente.setText("ENDEREÇO:");

        lbTelefoneCliente.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lbTelefoneCliente.setText("TELEFONE:");

        lbTextoNome.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbTextoNome.setText("CAIQUE CESAR DE GODOY");

        lbTextoEndereco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbTextoEndereco.setText("LAZARO DE LIMA, 63 - RAINHA DA PAZ");

        lbTextoTelefone.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbTextoTelefone.setText("(19) 3893-7846");

        javax.swing.GroupLayout pnDadosLayout = new javax.swing.GroupLayout(pnDados);
        pnDados.setLayout(pnDadosLayout);
        pnDadosLayout.setHorizontalGroup(
            pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNomeCliente)
                    .addComponent(lbTelefoneCliente)
                    .addComponent(lbEnderecoCliente))
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDadosLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(lbTextoTelefone))
                    .addGroup(pnDadosLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTextoEndereco)
                            .addComponent(lbTextoNome))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        pnDadosLayout.setVerticalGroup(
            pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeCliente)
                    .addComponent(lbTextoNome))
                .addGap(18, 18, 18)
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEnderecoCliente)
                    .addComponent(lbTextoEndereco))
                .addGap(18, 18, 18)
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelefoneCliente)
                    .addComponent(lbTextoTelefone))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnPedido.setBackground(new java.awt.Color(255, 255, 255));
        pnPedido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PEDIDO", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        lbTotalItens.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lbTotalItens.setText("TOTAL DE ITENS");

        lbTotalPedido.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lbTotalPedido.setText("TOTAL DO PEDIDO");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(10, 70));

        lbTextoTotalItens.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbTextoTotalItens.setText("000");

        lbTextoPrecoTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbTextoPrecoTotal.setText("R$ 000,00");

        javax.swing.GroupLayout pnPedidoLayout = new javax.swing.GroupLayout(pnPedido);
        pnPedido.setLayout(pnPedidoLayout);
        pnPedidoLayout.setHorizontalGroup(
            pnPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPedidoLayout.createSequentialGroup()
                .addGroup(pnPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPedidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbTotalItens))
                    .addGroup(pnPedidoLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lbTextoTotalItens)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTotalPedido)
                    .addComponent(lbTextoPrecoTotal))
                .addGap(110, 110, 110))
        );
        pnPedidoLayout.setVerticalGroup(
            pnPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnPedidoLayout.createSequentialGroup()
                            .addComponent(lbTotalPedido)
                            .addGap(32, 32, 32)
                            .addComponent(lbTextoPrecoTotal)
                            .addGap(15, 15, 15))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnPedidoLayout.createSequentialGroup()
                        .addComponent(lbTotalItens)
                        .addGap(33, 33, 33)
                        .addComponent(lbTextoTotalItens)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pnControle.setBackground(new java.awt.Color(240, 204, 153));

        btAddPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add.png"))); // NOI18N
        btAddPedido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btAddPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddPedidoActionPerformed(evt);
            }
        });

        btAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user_add.png"))); // NOI18N
        btAddUser.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddUserActionPerformed(evt);
            }
        });

        btVerRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Critical_details.png"))); // NOI18N
        btVerRelatorio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btVerRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerRelatorioActionPerformed(evt);
            }
        });

        btRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Refresh.png"))); // NOI18N
        btRefresh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        btSair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imprimir.png"))); // NOI18N
        btImprimir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pnControleLayout = new javax.swing.GroupLayout(pnControle);
        pnControle.setLayout(pnControleLayout);
        pnControleLayout.setHorizontalGroup(
            pnControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnControleLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btAddPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btVerRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnControleLayout.setVerticalGroup(
            pnControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btVerRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btAddPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btImprimir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo Delivery PNG.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnChamados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(pnPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pnControle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lbLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbLogo)
                .addGap(18, 18, 18)
                .addComponent(pnControle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnChamados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddUserActionPerformed

        if (frmCli == null){
            frmCli = new frmClientes();
        }
//        this.setEnabled(false);
        frmCli.setVisible(true);
        
    }//GEN-LAST:event_btAddUserActionPerformed

    private void btAddPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddPedidoActionPerformed
        
        if (frmPedido == null){
            frmPedido = new frmNovoPedido();
        }
//        this.setEnabled(false);
        frmPedido.setVisible(true);
    }//GEN-LAST:event_btAddPedidoActionPerformed

    private void btVerRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btVerRelatorioActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDeliveryInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDeliveryInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDeliveryInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDeliveryInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDeliveryInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddPedido;
    private javax.swing.JButton btAddUser;
    private javax.swing.JButton btImprimir;
    private javax.swing.JButton btRefresh;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btVerRelatorio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbEnderecoCliente;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbNomeCliente;
    private javax.swing.JLabel lbTelefoneCliente;
    private javax.swing.JLabel lbTextoEndereco;
    private javax.swing.JLabel lbTextoNome;
    private javax.swing.JLabel lbTextoPrecoTotal;
    private javax.swing.JLabel lbTextoTelefone;
    private javax.swing.JLabel lbTextoTotalItens;
    private javax.swing.JLabel lbTotalItens;
    private javax.swing.JLabel lbTotalPedido;
    private javax.swing.JPanel pnChamados;
    private javax.swing.JPanel pnControle;
    private javax.swing.JPanel pnDados;
    private javax.swing.JPanel pnPedido;
    private javax.swing.JTable tbChamados;
    // End of variables declaration//GEN-END:variables
}
